---
title: "multi-state-model-for-early-oncology"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{multi-state-model-for-early-oncology}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(bhmbasket.predict)
```

```{r}
tbl_visits <- tibble::tribble(
    ~group_id, ~subject_id,    ~t,        ~state,
            1,           1,     0,      "stable",
            1,           1,   1.2,      "stable",
            1,           1,   2.4,    "response",
            1,           1,   3.6, "progression",
            1,           2,     1,      "stable",
            1,           2,     2,      "stable",
            1,           2,     3,    "response",
            1,           3,   1.5,      "stable",
            1,           3,     3,    "response",
            1,           3,   3.5,         "EOF"
  )

tbl_mstate <- visits_to_mstate(
  tbl_visits,
  start_state = "stable",
  absorbing_states = c("progression")
)

tbl_mstate %>% 
  group_by(subject_id) %>% 
  mutate(tt_min = cumsum(dt_min), tt_max = cumsum(dt_max)) %>% print(n = Inf)

srp_plot(tbl_mstate)

mstate_to_visits(tbl_data, visit_spacing = 1.2)

tbl_data %>% 
  group_by(subject_id) %>% 
  mutate(t_min = cumsum(dt_min), t_max = cumsum(dt_max)) %>% print(n = Inf)
```


