// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// visits_to_tte_
DataFrame visits_to_tte_(DataFrame data);
RcppExport SEXP _bhmbasket_predict_visits_to_tte_(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(visits_to_tte_(data));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_stan_fit4IndependentMixtureCureRateModel_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4IndependentPoissonRecruitmentModel_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_bhmbasket_predict_visits_to_tte_", (DL_FUNC) &_bhmbasket_predict_visits_to_tte_, 1},
    {"_rcpp_module_boot_stan_fit4IndependentMixtureCureRateModel_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4IndependentMixtureCureRateModel_mod, 0},
    {"_rcpp_module_boot_stan_fit4IndependentPoissonRecruitmentModel_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4IndependentPoissonRecruitmentModel_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_bhmbasket_predict(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
