#' Plot a data sets of visits
#'
#' @param visit_data data frame as generated by [generate_visit_data]
#' @param epsilon numeric width (in months) of final status indicator
#' @param event_positive logical, is the event of interest positive (e.g. a response to treatment)? If TRUE, the events are coded in green.
#'
#' @export
plot_visits <- function(visit_data, epsilon = 5/30, event_positive = TRUE) {
  t_max <- max(visit_data$t)
  res <- visit_data %>%
    group_by(.data$subject_id) %>%
    mutate(
      t_end = case_when(
        row_number() == n() & !.data$eof ~ t_max + epsilon,
        row_number() == n() ~ .data$t + epsilon,
        row_number() != n() ~ lead(.data$t)
      )
    ) %>%
    ungroup() %>%
    rename(t_start = .data$t) %>%
    select(.data$subject_id, .data$group_id, .data$t_start, .data$t_end, .data$status, .data$eof)
  res <- res %>%
    group_by(.data$group_id) %>%
    mutate(
      subject_id = as.numeric(factor(.data$subject_id, levels = unique(.data$subject_id[order(.data$t_start)]))),
      group_id = factor(.data$group_id)
    )
  ggplot(res) +
    ggplot2::geom_rect(
      aes(
        xmin = .data$t_start, xmax = .data$t_end,
        ymin = as.numeric(.data$subject_id) - .5,
        ymax = as.numeric(.data$subject_id) + .5,
        fill = .data$status
      )
    ) +
    ggplot2::scale_fill_manual(
      "Status",
      values = if (event_positive) c(E = "darkgreen", S = "gray", N = "red") else c(N = "darkgreen", S = "gray", E = "red"),
      na.translate = FALSE
    ) +
    ggplot2::labs(
      x = "months since start of trial",
      y = "subject"
    ) +
    ggplot2::facet_wrap(~.data$group_id, scales = "free_y") +
    theme(
      legend.position = "top",
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.spacing = ggplot2::unit(.2, "lines"),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank()
    )
}
