# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

impute_srp_model <- function(df, response_probabilities, shapes, scales, visit_spacing, max_time) {
    .Call(`_oncomsm_impute_srp_model`, df, response_probabilities, shapes, scales, visit_spacing, max_time)
}

rtruncweibull <- function(shape, scale, a, b) {
    .Call(`_oncomsm_rtruncweibull`, shape, scale, a, b)
}

