# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

recist_to_tte_ <- function(data) {
    .Call(`_bhmbasket_predict_recist_to_tte_`, data)
}

